name: CI
on: [push, pull_request]

env:
  RUSTFLAGS: "--deny warnings"
  MIRIFLAGS: "-Zmiri-strict-provenance"

jobs:
  check_fmt:
    name: fmt ${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  ci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        task: [
          ['stable', '', 'test', '--all-features'],
          ['stable', 'clippy', 'clippy', '--all-targets --all-features'],
          ['nightly', 'miri', 'miri', 'test --all-features']
        ]

    name: ${{ matrix.task[0] }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.task[0] }}
          override: true
          components: ${{ matrix.task[1] }}

      - uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.task[2] }}
          args: ${{ matrix.task[3] }}
